### PR TITLE
Devel xsens

### PR DESCRIPTION
**Pull request by kouroshD**
As we discussed yesterday, I open this PR to merge my working activities from my fork to our shared repo on devel branch.
B.N. The code is not very clean now, mainly related to debugging and checking prints, but before merging to master I will clean them.

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
I think that you can continue to develop in your branch and then as soon as you are ready I'll start the review

**Comment by GiulioRomualdi** [comment]
@kouroshD can you rebase the branch on top of devel, so I can start the review?

**Comment by kouroshD** [comment]
Since I made a new branch for rebasing, I close this PR and open a new one.

**Comment by kouroshD** [comment]
The new PR: https://github.com/robotology/walking-teleoperation/pull/19

**Pull request closed without merging**
