### PR TITLE
Merge Devel into Master

### LINKED ISSUE #3: Take into account joint limits in fingers retargeting
The joint limits should be take into account for the finger retargeting. Indeed the desired position of the fingers are evaluated using an integrator 
https://github.com/robotology/walking-teleoperation/blob/515abfe571432b88610cd344c7c41082184294fe/modules/Oculus_module/src/FingersRetargeting.cpp#L47
Since the integrator is not saturated the desired joint position can exceed the limits.

I think that this can be easily fixed by setting the limits to the integrator object. Please check [here](http://www.icub.org/software_documentation/classiCub_1_1ctrl_1_1Integrator.html#a416b570ee6038b25f7706bd781d69b20) for further details 
https://github.com/robotology/walking-teleoperation/blob/515abfe571432b88610cd344c7c41082184294fe/modules/Oculus_module/src/FingersRetargeting.cpp#L34

### LINKED ISSUE #4: Use device interfaces instead of ports for getting input from oculus
It would be nice to use the oculus YARP [device](http://www.yarp.it/group__dev__iface.html) for getting the inputs instead of using YARP ports. 
https://github.com/robotology/walking-teleoperation/blob/515abfe571432b88610cd344c7c41082184294fe/modules/Oculus_module/src/OculusModule.cpp#L557-L564

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR:
close #4 
close #3

I created a [tag](https://github.com/robotology/walking-teleoperation/releases/tag/v0.1.0) that points to the last commit before this PR.

### CODE REVIEW

**Comment by traversaro** [comment]
With which yarp version is this compatible?

**Comment by kouroshD** [comment]
> With which yarp version is this compatible?

This repo is compatible with master branch of YARP.

**Comment by traversaro** [comment]
> This repo is compatible with master branch of YARP. 

Great!

**Comment by kouroshD** [comment]
> > This repo is compatible with master branch of YARP.
> 
> Great!

To be more precise, we are using CamCalibWithPose in windows machine which has dependencies to devel branch of yarp!

**Comment by traversaro** [comment]
> To be more precise, we are using CamCalibWithPose in windows machine which has dependencies to devel branch of yarp!

As long as it can be compiled with YARP master, I think it is ok.

**Pull request merged**
