### PR TITLE
Fix oculus xsens

### PR DESCRIPTION
**Pull request by kouroshD**
- fix the paramters for the joypad device
- remove imu option from `camCalibWithPose`
- remove the image orientation part since now the image is fixed wrt VR headset display
- remove the torso retargeting since it was only used for the image orientation in the case of xsens retargeting
- fix the head configuration in the case of  xsens retargeting in order not initialize it

### CODE REVIEW

**Review by S-Dafarra — APPROVED** [review]
I think you need to properly rebase on top of ``devel``. The modifications for the ``hde`` side should be already there.

**Comment by kouroshD** [comment]
Moreover, I have tested only two demos with the new changes, Xsens+ virtualizer+ Oculus Walking, and Oculus+ walking. However, it should be OK for other demos, but it might be better to test them before as well.

**Comment by kouroshD** [comment]
I rebased it on top of devel.

@S-Dafarra  @GiulioRomualdi  Should I merge, or we do a new round of tests before the merge?

**Comment by kouroshD** [comment]
Following the f2f discussion, I'll do proceed with the merge.

**Pull request merged**
