### PR TITLE
Xprize Semifinals testing yarpmanager application files updates

### PR DESCRIPTION
**Pull request by kouroshD**

### CODE REVIEW

**Comment by S-Dafarra** [comment]
@kouroshD can we proceed with this PR?

**Comment by kouroshD** [comment]
Yes I think, let me check this again first and I will put for review.

**Comment by S-Dafarra** [comment]
@kouroshD friendly ping

**Comment by kouroshD** [comment]
sounds good to me @S-Dafarra . Have a look on it as well, then we merge. thanks.

**Review by S-Dafarra — APPROVED** [review]
I have quickly checked them. I think we can proceed considering these were the files used for the Semifinals. We can improve in later PRs.

**Comment by kouroshD** [comment]
Rebased the branch, working for the jobs. Then will merge.

**Pull request merged**
