### PR TITLE
Fix deprecations of yarp methods

### PR DESCRIPTION
**Pull request by S-Dafarra**

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks!

**Comment by S-Dafarra** [comment]
I guess, there is still something missing, given the CI output. Then we need to merge devel in master and do a new release I guess, right?

**Comment by S-Dafarra** [comment]
Apparently, the failures are related to iDynTree. See https://github.com/robotology/idyntree/pull/992

**Comment by traversaro** [comment]
> Apparently, the failures are related to iDynTree. See [robotology/idyntree#992](https://github.com/robotology/idyntree/pull/992)

Good catch!

**Pull request merged**
