### PR TITLE
Rebased Devel branch on top of Master 

### PR DESCRIPTION
**Pull request by kouroshD**
In order the devel to master branch, we should first rebase the devel branch. This is the PR related to that.
Related issue: https://github.com/dic-iit/element_retargeting-from-human/issues/103

### CODE REVIEW

**Comment by kouroshD** [comment]
With this PR, I am trying to rebase the devel on master. Since there is this small commit https://github.com/robotology/walking-teleoperation/pull/34/commits/60b449e6e8d5120a2a11ca2997521f46c51821c1 on master. However, this means rewriting the history of devel which might not be pleasant to us.

However,  after rebasing in https://github.com/kouroshD/walking-teleoperation/tree/devel_rebased branch, and opening a PR, it was giving the conflict error and I fixed it with https://github.com/robotology/walking-teleoperation/pull/34/commits/cd6a57c1651cafd36e99bab0a4eaaffa4d0ae7ae commit. So, the question what is the best way to rebase the devel on master in this case.
1. push it with `-f` option to devel, and rewrite the history of devel.
2. use one of the options provided in this PR (i.e., create a merge commit, squash & merge,  rebase & merge).
3. as @traversaro  suggested, forward merge to bring the changes from the master to devel.
4. push the commit in master https://github.com/robotology/walking-teleoperation/pull/34/commits/60b449e6e8d5120a2a11ca2997521f46c51821c1 to devel, and revert the commit in master 

@traversaro  by forward merge, you mean merging the commit in master to devel, am I right?

However, as I see the second and third option there will be conflict when merging the devel to master, eventually.

**Comment by traversaro** [comment]
> @traversaro by forward merge, you mean merging the commit in master to devel, am I right?

Yes, I mean first ensuring that both master and devel are up-to-date locally, and then run:
~~~
git checkout devel
git merge master
~~~

> However, as I see the second and third option there will be conflict when merging the devel to master, eventually.

I guess the conflicts needs to be fixed, or for some reason fixing the conflicts is complicated?

**Comment by kouroshD** [comment]
> > However, as I see the second and third option there will be conflict when merging the devel to master, eventually.
> 
> I guess the conflicts needs to be fixed, or for some reason fixing the conflicts is complicated?

Merging is easy. The problem is that, in this case, after merging master to devel, when we want to merge the devel to master, we should push it with `-f` option, am I right!? Since we are going to rewrite the master history?!

**Comment by traversaro** [comment]
> 
> 
> > > However, as I see the second and third option there will be conflict when merging the devel to master, eventually.
> > 
> > 
> > I guess the conflicts needs to be fixed, or for some reason fixing the conflicts is complicated?
> 
> @traversaro Merging is easy. The problem is that, in this case, after merging master to devel, when we want to merge the devel to master, we should push it with `-f` option, am I right!? Since we are going to rewrite the master history?!

No, tipically we never rewrite history on the `master` branch, but we  actually keep the merge commit.

**Comment by kouroshD** [comment]
I have opened a new PR https://github.com/robotology/walking-teleoperation/pull/35 from devel to master, and directly there the conflicts are fixed and added to devel branch.
So, I'll close this PR without merging.
Thanks @GiulioRomualdi  and @traversaro  for the clarification.

**Pull request closed without merging**
