### PR TITLE
Merge Devel to Master

### PR DESCRIPTION
**Pull request by kouroshD**
Merging devel to master.

### CODE REVIEW

**Comment by kouroshD** [comment]
Waiting for the GitHub actions and then merging.

**Comment by S-Dafarra** [comment]
I wonder if it could make sense to merge https://github.com/robotology/walking-teleoperation/pull/75 first since it fixes a couple of problems with the applications

**Comment by kouroshD** [comment]
The new file names related to the `JoypadControlServer` device parameters is called `dcmWalkingRetargeting.ini`. Probably, it is copy-pasting problem, since the configuration file name is misleading. Probably, sth like `JoypadControlServerParameters.ini` can be better representative of those parameters.

**Comment by kouroshD** [comment]
I have reviewed both #75 and #76 (since #76  was blocking #75) . As soon as @S-Dafarra  looks of the reviews, we can merge them to the devel. Upon those additions, I Will merge the devel to the master and make a new release.

cc @GiulioRomualdi  @traversaro

**Comment by kouroshD** [comment]
We merged those PRs. Waiting for the github actions, and then I will merge the devel to master.

**Review by S-Dafarra — APPROVED** [review]

**Review by traversaro — APPROVED** [review]

**Comment by kouroshD** [comment]
Following the results of the github action in https://github.com/robotology/walking-teleoperation/actions/runs/1525185088, I am going to merge the code.

**Pull request merged**
