### PR TITLE
Texture retargeting

### PR DESCRIPTION
**Pull request by kouroshD**
Probably we need to rebase on top of `devel` due to https://github.com/robotology/walking-teleoperation/pull/97.

As I mentioned before, I do not set up my systems now, so I cannot do it now.
@S-Dafarra  you can simply rebase it on top of `devel`, and build to check. You should also fix the deprecation problems as in https://github.com/robotology/walking-teleoperation/pull/97 later. If you cannot, I can do it in these days, but not today for sure.
**Avoid doing any squashing, I would like to keep the commit history clean.**

### CODE REVIEW

**Comment by S-Dafarra** [comment]
> @S-Dafarra you can simply rebase it on top of `devel`, and build to check.

Done. I also changed the base branch to ``master``



> You should also fix the deprecation problems as in #97

Done in https://github.com/robotology/walking-teleoperation/pull/100/commits/2fa747650467d912c175c09a6bd095e0182e0c51

**Review by S-Dafarra — APPROVED** [review]
Given the circumstances, we can simply merge this PR as is once the CI passes

**Comment by kouroshD** [comment]
> Given the circumstances, we can simply merge this PR as is once the CI passes

If you want to have a look to the PR and code (however, it is a bit large), I invite you to do so. If there are suggestions, I can fix it in the following days. In any case, I have been carefully updated the code to be clean and with clear necessary explanation and documentation.

I am also available later on, if you have some doubts or feedbacks!

**Comment by kouroshD** [comment]
Should I continue with the merge @S-Dafarra ?!

**Comment by S-Dafarra** [comment]
I quickly skimmed through the code and seems good to me! I also appreciated the documentation in the configuration files and in the code! Thanks a million, @kouroshD. Merging!

**Pull request merged**
